#!/bin/bash
output=a.swf

while getopts 'hvo:' opt; do
    case $opt in
	o)
	    output=$OPTARG;;
	v)
	    echo "HappyABC compiler, version <Version>"
	    exit 0;;
	h)
	    cat <<EOF
Usage: $0 [options] [--] wsourcefile

  -oFILE          set output file name
  -h              print this help and exit
  -v              print the version and exit
EOF
	    exit 0;;
    esac
done
shift  $(($OPTIND - 1))

Temp=$output.$$
base=$(basename $output)
habc-core -o $Temp $1

XML=$(habc-xml $Temp)
Label=Main

cat <<EOF | swfmill xml2swf stdin $output
<swf version="9" compressed="1">
  <Header framerate="24" frames="1">
    <size>
      <Rectangle left="0" right="10000" top="0" bottom="7500"/>
    </size>
    <tags>
      <FileAttributes hasMetaData="1" allowABC="1" suppressCrossDomainCaching="0" swfRelativeURLs="0" useNetwork="1"/>
      <SetBackgroundColor>
        <color>
          <Color red="134" green="156" blue="167"/>
        </color>
      </SetBackgroundColor>
      <FrameLabel label="${Label}">
        <flags/>
      </FrameLabel>
      <DoABCDefine flags="1" name="frame1">
        <actions>${XML}</actions>
      </DoABCDefine>
      <SymbolClass>
        <symbols>
          <Symbol objectID="0" name="${Label}"/>
        </symbols>
      </SymbolClass>
      <ShowFrame/>
      <End/>
    </tags>
  </Header>
</swf>
EOF

rm $Temp